# Generated by Django 2.1.2 on 2018-10-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Days',
            new_name='Day',
        ),
    ]
